// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12/17/2025, 3:30:57 AM
const configMerger = require("/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/plugins/**/*.{js,ts,mjs}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/composables/**/*.{js,ts,mjs}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/utils/**/*.{js,ts,mjs}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/tr1la/Documents/LLMProj/LLM_GitApp/Frontend/app.config.{js,ts,mjs}"] } }));

module.exports = config
